### ISSUE TITLE
请问一下？

### ISSUE THREAD

**Issue by h82258652** [chenrensong/Encoding.UWP#1]
我英文不是很好。
请问一下这个项目是获取GB2312等编码吗？
那么跟
```C#
EncodingProvider provider = CodePagesEncodingProvider.Instance;
Encoding.RegisterProvider(provider);
Encoding gb2312 = Encoding.GetEncoding("gb2312");
```
的区别是？

**Comment by chenrensong** [comment]
两种做法都可以获取到GB2312编码，直接用CodePagesEncodingProvider基本就能获取桌面平台所有的编码，包括BIG5、GB2312等编码，而Encoding.UWP这种方法适合扩展新的编码，如果没有特别的需求在UWP应用中直接用系统的就可以。

**Comment by h82258652** [comment]
谢谢解答！
